### PR TITLE
Added unit tests again with autocrlf enabled

### PR DESCRIPTION
**Pull request by mightyshazam**
**Summary**
This PR adds unit tests for the converters and classes in Temporal.SDK.Common. It uncovered what I believe to be an issue with the VoidPayloadConverter. It was returning true in all cases, so that meant the CompositePayloadConverter would never go through all of its options.

**Related Work Items**
#13 

## What was changed
Changed the VoidPayloadConverter to return false when its preconditions fails

## Why?
There are currently no tests within the project.

### CODE REVIEW

**Comment by mightyshazam** [comment]
@macrogreg This PR should fix the line ending issue from the previous PR. #51

**Comment by macrogreg** [comment]
Hi @mightyshazam , thanks for the update for being on top of the latest changes. Since this PR now includes changes in increments upon, the code delta is not all relevant.
To make things easier, I created this: https://github.com/macrogreg/sdk-dotnet/pull/1
That is a PR from your branch into the branch you based your work upon. So it contain only the delta that is your actual change. I will be doing the review there, so that we can focus only on the relevant changes. :)

**Review by macrogreg — APPROVED** [review]
Thanks, @mightyshazam, for the contribution.
We have merged all the previous items, so this can go next. I did not want to touch your branch without synching with your first, but as soon as you sync the branch, the delta here will become relevant to only this change. However, util then I have revied the placeholder PR (https://github.com/macrogreg/sdk-dotnet/pull/1) to focus on the delta.

I think the only comments that require to be addresses is this:
https://github.com/macrogreg/sdk-dotnet/pull/1/files#r872904901

I suggest to address all the rest afterwards. Just want to make sure you are OK with modifying your contribution so soon after a merge. Also, please feel free to push back on any of the comments.

Approving. Please feel free to merge as soon as the line endings are fixed. :)

**Comment by macrogreg** [comment]
I am so sorry @mightyshazam, I typed a comment into a wrong, pressed enter and this got merged. My mistake, I wanted to leave it to you do to the honors, I apologize.

**Pull request merged**
