### PR TITLE
GH CI action

### PR DESCRIPTION
**Pull request by cretz**
## What was changed

GH CI setup

### CODE REVIEW

**Comment by cretz** [comment]
Marking ready for review because I can't get the actions to run. Will fix in next PR

**Comment by Quinn-With-Two-Ns** [comment]
I looked at your repo and saw this error https://github.com/cretz/temporal-sdk-dotnet/actions/runs/3858376629/workflow

**Review by Quinn-With-Two-Ns — APPROVED** [review]

**Review by mindaugasrukas — APPROVED** [review]

**Comment by cretz** [comment]
@Quinn-With-Two-Ns - Thanks! I thought I fixed that, checking. Didn't think to check my fork repo.

**Comment by cretz** [comment]
Closing in favor of same-repo branch

**Pull request closed without merging**
